### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/my-website#1]
# Motivation
We want to be able to host my new website on a cloud domain, Heroku. This will give me complete control of how my website will look. For now, we just want to link the page to a DNS provider and have a page that says hello world.

# Task Implementation
- [x] Import dependencies.
- [x] Get all the files set up for running the website locally.
- [x] Be able to run the app locally.
- [x] Be able to deploy the app to heroku.
