### ISSUE TITLE
Modernize Website

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/my-website#10]
# Motivation
We want to be able modernize the website that I show for people. Now that I'm in SLC I want to update it plus make the webpage load much faster by using Preact.

# Tasks
- [x] Update where I am located.
- [x] Use preact material ui.
- [x] Use my preactx plugin.
