### ISSUE TITLE
Users can see my homepage

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/my-website#3]
# Motivation
Now that we have a basic working demo of my homepage, we want to be able to be able to see a landing page that describes who I am in a very simple yet effective manner.

# Task Implementation
- [ ] Decide how I want the page to be presented.
- [ ] Decide on a UI framework (Maybe Blueprint JS?)
- [ ] Be able to leverage dynamic and reusable components.
