### ISSUE TITLE
Add a music player to my homepage

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/my-website#5]
# Motivation
We want to have a single song be playable.

# Task Implementation
- [ ] Research what is necessary to be able to play songs.
- [ ] Pick a track.
- [ ] Be able to import the track to my website.
- [ ] Add the player to the navbar.
- [ ] Be able to play the song from the page.
