### ISSUE TITLE
Fix issues with the Header Colors and positionings

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/my-website#6]
# Motivation
The Header should have its own color, separate from that of the picture container.

# Task Implementation
- [x] Use a light background for the header.
- [x] Implement 12px rules for visual rhythm.
- [x] Change resume link.
